// Licensed under the Apache-2.0 license

use core::fmt::Write;
use mcu_error::{McuError, McuResult};
use registers_generated::lc_ctrl;
use romtime::{HexWord, StaticRef};
use tock_registers::interfaces::{Readable, Writeable};

// TODO: fix the autogenerated offsets
// const LC_TOKENS_OFFSET: usize = fuses::SECRET_LC_TRANSITION_PARTITION_BYTE_OFFSET;
pub(crate) const LC_TOKENS_OFFSET: usize = 0x4a0;

/// Unhashed token, suitable for doing lifecycle transitions.
#[derive(Clone, Copy)]
pub struct LifecycleToken(pub [u8; 16]);

impl From<[u8; 16]> for LifecycleToken {
    fn from(value: [u8; 16]) -> Self {
        LifecycleToken(value)
    }
}

impl From<LifecycleToken> for [u8; 16] {
    fn from(value: LifecycleToken) -> Self {
        value.0
    }
}

/// Raw tokens
pub struct LifecycleRawTokens {
    pub test_unlock: [LifecycleToken; 7],
    pub manuf: LifecycleToken,
    pub manuf_to_prod: LifecycleToken,
    pub prod_to_prod_end: LifecycleToken,
    pub rma: LifecycleToken,
}

/// Hashed token, suitable for burning into the OTP.
#[derive(Clone, Copy)]
pub struct LifecycleHashedToken(pub [u8; 16]);

impl From<[u8; 16]> for LifecycleHashedToken {
    fn from(value: [u8; 16]) -> Self {
        LifecycleHashedToken(value)
    }
}

impl From<LifecycleHashedToken> for [u8; 16] {
    fn from(value: LifecycleHashedToken) -> Self {
        value.0
    }
}

/// Hashed tokens to be burned into the OTP for lifecycle transitions.
pub struct LifecycleHashedTokens {
    pub test_unlock: [LifecycleHashedToken; 7],
    pub manuf: LifecycleHashedToken,
    pub manuf_to_prod: LifecycleHashedToken,
    pub prod_to_prod_end: LifecycleHashedToken,
    pub rma: LifecycleHashedToken,
}

pub use mcu_otp_lifecycle::LifecycleControllerState;

pub struct Lifecycle {
    registers: StaticRef<lc_ctrl::regs::LcCtrl>,
}

impl Lifecycle {
    pub const fn new(registers: StaticRef<lc_ctrl::regs::LcCtrl>) -> Self {
        Lifecycle { registers }
    }

    pub fn init(&self) -> McuResult<()> {
        romtime::println!("[mcu-lcc] Initializing Lifecycle controller...");
        while !self.registers.status.is_set(lc_ctrl::bits::Status::Ready) {}
        while !self
            .registers
            .status
            .is_set(lc_ctrl::bits::Status::Initialized)
        {}

        romtime::println!(
            "[mcu-lcc] Lifecycle state: {} (count {})",
            HexWord(self.registers.lc_state.get() & 0x1f),
            self.registers.lc_transition_cnt.get()
        );

        romtime::println!("Lifecycle controller initialization done");
        Ok(())
    }

    pub fn status(&self) -> u32 {
        self.registers.status.get()
    }

    pub fn calc_lc_state_mnemonic(state: LifecycleControllerState) -> u32 {
        let state = u8::from(state);
        let next_lc_state_5bit = (state & 0x1F) as u32;

        (next_lc_state_5bit << 25)
            | (next_lc_state_5bit << 20)
            | (next_lc_state_5bit << 15)
            | (next_lc_state_5bit << 10)
            | (next_lc_state_5bit << 5)
            | next_lc_state_5bit
    }

    pub fn transition(
        &self,
        state: LifecycleControllerState,
        token: &LifecycleToken,
    ) -> McuResult<()> {
        romtime::println!(
            "[mcu-rom-lcc] Transitioning Lifecycle state... to {}",
            u8::from(state)
        );
        let next_lc_state_mne = Self::calc_lc_state_mnemonic(state);
        let token = u128::from_le_bytes(token.0);

        const MULTI_TRUE: u32 = 0x96;

        // Step 1: Set Claim Transition Register
        while self.registers.claim_transition_if.get() != MULTI_TRUE {
            self.registers.claim_transition_if.set(MULTI_TRUE);
            let reg_value = self.registers.claim_transition_if.get();
            romtime::println!(
                "[mcu-rom-lcc] Claim Mutex Register: {} (should be {})",
                HexWord(reg_value),
                HexWord(MULTI_TRUE)
            );
        }
        romtime::println!("[mcu-rom-lcc] Mutex successfully acquired.");

        // Step 3: Set Target Lifecycle State
        romtime::println!(
            "[mcu-rom-lcc] Setting next lifecycle state: 0x{:02x}",
            next_lc_state_mne & 0x1f
        );
        self.registers.transition_target.set(next_lc_state_mne);

        // Step 4: Write Transition Tokens
        let token_31_0 = (token & 0xFFFF_FFFF) as u32;
        let token_63_32 = ((token >> 32) & 0xFFFF_FFFF) as u32;
        let token_95_64 = ((token >> 64) & 0xFFFF_FFFF) as u32;
        let token_127_96 = ((token >> 96) & 0xFFFF_FFFF) as u32;

        romtime::println!("[mcu-rom-lcc] Writing tokens: 0x{:08x}", token_31_0);
        self.registers.transition_token_0.set(token_31_0);
        romtime::println!("[mcu-rom-lcc] Writing tokens: 0x{:08x}", token_63_32);
        self.registers.transition_token_1.set(token_63_32);
        romtime::println!("[mcu-rom-lcc] Writing tokens: 0x{:08x}", token_95_64);
        self.registers.transition_token_2.set(token_95_64);
        romtime::println!("[mcu-rom-lcc] Writing tokens: 0x{:08x}", token_127_96);
        self.registers.transition_token_3.set(token_127_96);

        // Step 6: Trigger the Transition Command
        romtime::println!("[mcu-rom-lcc] Triggering transition command: 0x1",);
        self.registers.transition_cmd.set(1);

        // Step 7: Poll Status Register
        loop {
            let status = self.registers.status.extract();
            romtime::println!(
                "[mcu-rom-lcc] Polling status register: {}",
                HexWord(status.get())
            );

            if status.is_set(lc_ctrl::bits::Status::TransitionSuccessful) {
                romtime::println!("[mcu-rom-lcc] Transition successful.");
                break;
            }
            if status.is_set(lc_ctrl::bits::Status::TransitionError) {
                romtime::println!("[mcu-rom-lcc] Transition error detected.");
                return Err(McuError::ROM_LC_TRANSITION_ERROR);
            }
            if status.is_set(lc_ctrl::bits::Status::TokenError) {
                romtime::println!("[mcu-rom-lcc] Token error detected.");
                return Err(McuError::ROM_LC_TOKEN_ERROR);
            }
            if status.is_set(lc_ctrl::bits::Status::OtpError) {
                romtime::println!("[mcu-rom-lcc] OTP error detected.");
                return Err(McuError::ROM_LC_OTP_ERROR);
            }
            if status.is_set(lc_ctrl::bits::Status::FlashRmaError) {
                romtime::println!("[mcu-rom-lcc] FLASH RMA error detected.");
                return Err(McuError::ROM_LC_FLASH_RMA_ERROR);
            }
            if status.is_set(lc_ctrl::bits::Status::TransitionCountError) {
                romtime::println!("[mcu-rom-lcc] Transition count error detected.");
                return Err(McuError::ROM_LC_TRANSITION_COUNT_ERROR);
            }
            if status.is_set(lc_ctrl::bits::Status::StateError) {
                romtime::println!("[mcu-rom-lcc] State error detected.");
                return Err(McuError::ROM_LC_STATE_ERROR);
            }
            if status.is_set(lc_ctrl::bits::Status::BusIntegError) {
                romtime::println!("[mcu-rom-lcc] Bus integrity error detected.");
                return Err(McuError::ROM_LC_BUS_INTEG_ERROR);
            }
            if status.is_set(lc_ctrl::bits::Status::OtpPartitionError) {
                romtime::println!("[mcu-rom-lcc] OTP partition error detected.");
                return Err(McuError::ROM_LC_OTP_PARTITION_ERROR);
            }
        }

        self.registers.claim_transition_if.set(0);

        romtime::println!("[mcu-rom-lcc] Lifecycle state transitioned");
        Ok(())
    }
}
