// Licensed under the Apache-2.0 license

pub const EMULATOR_RUNTIME_TEST_FEATURES: &[&str] = &[
    "test-i3c-simple",
    "test-i3c-constant-writes",
    "test-mctp-capsule-loopback",
    "test-firmware-update-streaming",
    "test-firmware-update-flash",
    "test-flash-based-boot",
    "test-pldm-streaming-boot",
    "test-pldm-fw-update-e2e",
    "test-do-nothing",
    "test-caliptra-certs",
    "test-caliptra-crypto",
    "test-caliptra-mailbox",
    "test-dma",
    "test-doe-transport-loopback",
    "test-doe-user-loopback",
    "test-doe-discovery",
    "test-get-device-state",
    "test-flash-ctrl-init",
    "test-flash-ctrl-read-write-page",
    "test-flash-ctrl-erase-page",
    "test-flash-storage-read-write",
    "test-flash-storage-erase",
    "test-flash-usermode",
    "test-log-flash-linear",
    "test-log-flash-circular",
    "test-log-flash-usermode",
    "test-mctp-ctrl-cmds",
    "test-mctp-vdm-cmds",
    "test-pldm-discovery",
    "test-pldm-fw-update",
    "test-mci",
    "test-mcu-mbox-driver",
    "test-mcu-mbox-soc-requester-loopback",
    "test-mbox-sram",
    "test-warm-reset",
    "test-exit-immediately",
    "test-mcu-rom-flash-access",
    "test-mcu-svn-gt-fuse",
    "test-mcu-svn-lt-fuse",
];

pub const FPGA_RUNTIME_TEST_FEATURES: &[&str] = &[
    "test-i3c-simple",
    "test-i3c-constant-writes",
    "test-mctp-capsule-loopback",
    "test-fpga-flash-ctrl",
    "test-pldm-fw-update-e2e",
    "test-firmware-update-streaming",
    "test-mcu-mbox-usermode",
    "test-mcu-mbox-cmds",
    "test-mctp-vdm-cmds",
    "test-mcu-mbox-fips-self-test",
    "test-mcu-mbox-fips-periodic",
    "test-exit-immediately",
];
